#pragma once
#include "FST.h"

#define L_LEFTSIGMA 2,\
FST::NODE(1,FST::RELATION('<',1)),\
FST::NODE()

#define L_RIGHTSIGMA 2,\
FST::NODE(1,FST::RELATION('>',1)),\
FST::NODE()

#define L_LIBRARY 9,\
FST::NODE(1,FST::RELATION('#',1)),\
FST::NODE(1,FST::RELATION('l',2)),\
FST::NODE(1,FST::RELATION('i',3)),\
FST::NODE(1,FST::RELATION('b',4)),\
FST::NODE(1,FST::RELATION('r',5)),\
FST::NODE(1,FST::RELATION('a',6)),\
FST::NODE(1,FST::RELATION('r',7)),\
FST::NODE(1,FST::RELATION('y',8)),\
FST::NODE()


#define L_BYTE 5,\
FST::NODE(1, FST::RELATION('b', 1)),\
FST::NODE(1, FST::RELATION('y', 2)),\
FST::NODE(1, FST::RELATION('t', 3)),\
FST::NODE(1, FST::RELATION('e', 4)),\
FST::NODE()


#define L_NUMBERLITERALDEC 4, \
FST::NODE(1,FST::RELATION('$',1)),\
FST::NODE(1,FST::RELATION('8',2)),\
FST::NODE(16,\
	FST::RELATION('0', 2),\
	FST::RELATION('1', 2),\
	FST::RELATION('2', 2),\
	FST::RELATION('3', 2),\
	FST::RELATION('4', 2),\
	FST::RELATION('5', 2),\
	FST::RELATION('6', 2),\
	FST::RELATION('7', 2),\
	FST::RELATION('0', 3),\
	FST::RELATION('1', 3),\
	FST::RELATION('2', 3),\
	FST::RELATION('3', 3),\
	FST::RELATION('4', 3),\
	FST::RELATION('5', 3),\
	FST::RELATION('6', 3),\
	FST::RELATION('7', 3)\
),\
FST::NODE()

#define L_NUMBERLITERALBIN 4,\
FST::NODE(1,FST::RELATION('$',1)),\
FST::NODE(1,FST::RELATION('2',2)),\
FST::NODE(4,\
	FST::RELATION('0',2),\
	FST::RELATION('1',2),\
	FST::RELATION('0', 3),\
	FST::RELATION('1', 3)\
),\
FST::NODE()


#define L_STRINGLITERAL 4, \
FST::NODE(2, FST::RELATION('\"', 1), FST::RELATION('\"', 2)),\
	FST::NODE(189,	\
	FST::RELATION('a', 1), FST::RELATION('b', 1), FST::RELATION('c', 1), FST::RELATION('d', 1), FST::RELATION('e', 1), FST::RELATION('f', 1),\
	FST::RELATION('g', 1), FST::RELATION('h', 1), FST::RELATION('i', 1), FST::RELATION('j', 1), FST::RELATION('k', 1), FST::RELATION('l', 1),\
	FST::RELATION('m', 1), FST::RELATION('n', 1), FST::RELATION('o', 1), FST::RELATION('p', 1), FST::RELATION('q', 1), FST::RELATION('r', 1),\
	FST::RELATION('s', 1), FST::RELATION('t', 1), FST::RELATION('u', 1), FST::RELATION('v', 1), FST::RELATION('w', 1), FST::RELATION('x', 1),\
	FST::RELATION('y', 1), FST::RELATION('z', 1), FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1),\
	FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1), FST::RELATION('I', 1), FST::RELATION('J', 1), \
	FST::RELATION('K', 1), FST::RELATION('L', 1), FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1),\
	FST::RELATION('Q', 1), FST::RELATION('R', 1),FST::RELATION('S', 1), FST::RELATION('T', 1), FST::RELATION('U', 1), FST::RELATION('V', 1),\
	FST::RELATION('W', 1), FST::RELATION('X', 1),FST::RELATION('y', 1), FST::RELATION('z', 1),\
	FST::RELATION('1', 1), FST::RELATION('2', 1), FST::RELATION('3', 1), FST::RELATION('4', 1),\
	FST::RELATION('5', 1), FST::RELATION('6', 1), FST::RELATION('7', 1), FST::RELATION('8', 1), FST::RELATION('9', 1), FST::RELATION('0', 1),\
	\
	FST::RELATION('à', 1), FST::RELATION('á', 1), FST::RELATION('â', 1), FST::RELATION('ã', 1), FST::RELATION('ä', 1), FST::RELATION('å', 1),\
	FST::RELATION('¸', 1), FST::RELATION('æ', 1), FST::RELATION('ç', 1), FST::RELATION('è', 1), FST::RELATION('é', 1), FST::RELATION('ê', 1),\
	FST::RELATION('ë', 1), FST::RELATION('ì', 1), FST::RELATION('í', 1), FST::RELATION('î', 1), FST::RELATION('ï', 1), FST::RELATION('ð', 1),\
	FST::RELATION('ñ', 1), FST::RELATION('ò', 1), FST::RELATION('ó', 1), FST::RELATION('ô', 1), FST::RELATION('õ', 1), FST::RELATION('ö', 1),\
	FST::RELATION('÷', 1), FST::RELATION('ø', 1), FST::RELATION('ù', 1), FST::RELATION('ú', 1), FST::RELATION('û', 1), FST::RELATION('ü', 1),\
	FST::RELATION('ý', 1), FST::RELATION('þ', 1), FST::RELATION('ÿ', 1), FST::RELATION(' ', 1), FST::RELATION('.', 1), FST::RELATION(',', 1),\
	FST::RELATION('?', 1), FST::RELATION('!', 1), FST::RELATION(';', 1), FST::RELATION(':', 1), FST::RELATION('-', 1), FST::RELATION(')', 1),\
	FST::RELATION('(', 1),FST::RELATION('/', 1),FST::RELATION('%', 1),FST::RELATION('\n',1), \
	\
	FST::RELATION('a', 2), FST::RELATION('b', 2), FST::RELATION('c', 2), FST::RELATION('d', 2), FST::RELATION('e', 2), FST::RELATION('f', 2),\
	FST::RELATION('g', 2), FST::RELATION('h', 2), FST::RELATION('i', 2), FST::RELATION('j', 2), FST::RELATION('k', 2), FST::RELATION('l', 2),\
	FST::RELATION('m', 2), FST::RELATION('n', 2), FST::RELATION('o', 2), FST::RELATION('p', 2), FST::RELATION('q', 2), FST::RELATION('r', 2),\
	FST::RELATION('s', 2), FST::RELATION('t', 2), FST::RELATION('u', 2), FST::RELATION('v', 2), FST::RELATION('w', 2), FST::RELATION('x', 2),\
	FST::RELATION('y', 2), FST::RELATION('z', 2), FST::RELATION('1', 2), FST::RELATION('2', 2), FST::RELATION('3', 2), FST::RELATION('4', 2),\
	FST::RELATION('5', 2), FST::RELATION('6', 2), FST::RELATION('7', 2), FST::RELATION('8', 2), FST::RELATION('9', 2), FST::RELATION('0', 2),\
	\
	FST::RELATION('à', 2), FST::RELATION('á', 2), FST::RELATION('â', 2), FST::RELATION('ã', 2), FST::RELATION('ä', 2), FST::RELATION('å', 2),\
	FST::RELATION('¸', 2), FST::RELATION('æ', 2), FST::RELATION('ç', 2), FST::RELATION('è', 2), FST::RELATION('é', 2), FST::RELATION('ê', 2),\
	FST::RELATION('ë', 2), FST::RELATION('ì', 2), FST::RELATION('í', 2), FST::RELATION('î', 2), FST::RELATION('ï', 2), FST::RELATION('ð', 2),\
	FST::RELATION('ñ', 2), FST::RELATION('ò', 2), FST::RELATION('ó', 2), FST::RELATION('ô', 2), FST::RELATION('õ', 2), FST::RELATION('ö', 2),\
	FST::RELATION('÷', 2), FST::RELATION('ø', 2), FST::RELATION('ù', 2), FST::RELATION('ú', 2), FST::RELATION('û', 2), FST::RELATION('ü', 2),\
	FST::RELATION('ý', 2), FST::RELATION('þ', 2), FST::RELATION('ÿ', 2), FST::RELATION(' ', 2), FST::RELATION('.', 2), FST::RELATION(',', 2),\
	FST::RELATION('?', 2), FST::RELATION('!', 2), FST::RELATION(';', 2), FST::RELATION(':', 2), FST::RELATION('-', 2), FST::RELATION(')', 2),\
	FST::RELATION('(', 2),FST::RELATION('/', 2),FST::RELATION('%', 2)),\
	\
	FST::NODE(1, FST::RELATION('\"', 3)),\
	FST::NODE()

#define L_IDENTIFICATOR 2, \
FST::NODE(107,\
	FST::RELATION('_', 1),\
	FST::RELATION('a', 0),\
	FST::RELATION('b', 0),\
	FST::RELATION('c', 0),\
	FST::RELATION('d', 0),\
	FST::RELATION('e', 0),\
	FST::RELATION('f', 0),\
	FST::RELATION('g', 0),\
	FST::RELATION('h', 0),\
	FST::RELATION('i', 0),\
	FST::RELATION('j', 0),\
	FST::RELATION('k', 0),\
	FST::RELATION('l', 0),\
	FST::RELATION('m', 0),\
	FST::RELATION('n', 0),\
	FST::RELATION('o', 0),\
	FST::RELATION('p', 0),\
	FST::RELATION('q', 0),\
	FST::RELATION('r', 0),\
	FST::RELATION('s', 0),\
	FST::RELATION('t', 0),\
	FST::RELATION('u', 0),\
	FST::RELATION('v', 0),\
	FST::RELATION('w', 0),\
	FST::RELATION('x', 0),\
	FST::RELATION('y', 0),\
	FST::RELATION('z', 0),\
	FST::RELATION('A', 0),\
	FST::RELATION('B', 0),\
	FST::RELATION('C', 0),\
	FST::RELATION('D', 0),\
	FST::RELATION('E', 0),\
	FST::RELATION('F', 0),\
	FST::RELATION('G', 0),\
	FST::RELATION('H', 0),\
	FST::RELATION('I', 0),\
	FST::RELATION('J', 0),\
	FST::RELATION('K', 0),\
	FST::RELATION('L', 0),\
	FST::RELATION('M', 0),\
	FST::RELATION('N', 0),\
	FST::RELATION('O', 0),\
	FST::RELATION('P', 0),\
	FST::RELATION('Q', 0),\
	FST::RELATION('R', 0),\
	FST::RELATION('S', 0),\
	FST::RELATION('T', 0),\
	FST::RELATION('U', 0),\
	FST::RELATION('V', 0),\
	FST::RELATION('W', 0),\
	FST::RELATION('X', 0),\
	FST::RELATION('Y', 0),\
	FST::RELATION('Z', 0),\
	FST::RELATION('a', 1),\
	FST::RELATION('b', 1),\
	FST::RELATION('c', 1),\
	FST::RELATION('d', 1),\
	FST::RELATION('e', 1),\
	FST::RELATION('f', 1),\
	FST::RELATION('g', 1),\
	FST::RELATION('h', 1),\
	FST::RELATION('i', 1),\
	FST::RELATION('j', 1),\
	FST::RELATION('k', 1),\
	FST::RELATION('l', 1),\
	FST::RELATION('m', 1),\
	FST::RELATION('n', 1),\
	FST::RELATION('o', 1),\
	FST::RELATION('p', 1),\
	FST::RELATION('q', 1),\
	FST::RELATION('r', 1),\
	FST::RELATION('s', 1),\
	FST::RELATION('t', 1),\
	FST::RELATION('u', 1),\
	FST::RELATION('v', 1),\
	FST::RELATION('w', 1),\
	FST::RELATION('x', 1),\
	FST::RELATION('y', 1),\
	FST::RELATION('z', 1),\
	FST::RELATION('A', 1),\
	FST::RELATION('B', 1),\
	FST::RELATION('C', 1),\
	FST::RELATION('D', 1),\
	FST::RELATION('E', 1),\
	FST::RELATION('F', 1),\
	FST::RELATION('G', 1),\
	FST::RELATION('H', 1),\
	FST::RELATION('I', 1),\
	FST::RELATION('J', 1),\
	FST::RELATION('K', 1),\
	FST::RELATION('L', 1),\
	FST::RELATION('M', 1),\
	FST::RELATION('N', 1),\
	FST::RELATION('O', 1),\
	FST::RELATION('P', 1),\
	FST::RELATION('Q', 1),\
	FST::RELATION('R', 1),\
	FST::RELATION('S', 1),\
	FST::RELATION('T', 1),\
	FST::RELATION('U', 1),\
	FST::RELATION('V', 1),\
	FST::RELATION('W', 1),\
	FST::RELATION('X', 1),\
	FST::RELATION('Y', 1),\
	FST::RELATION('Z', 1)),\
	FST::NODE()

#define L_STRING 7,\
FST::NODE(1, FST::RELATION('s', 1)),\
FST::NODE(1, FST::RELATION('t', 2)),\
FST::NODE(1, FST::RELATION('r', 3)),\
FST::NODE(1, FST::RELATION('i', 4)),\
FST::NODE(1, FST::RELATION('n', 5)),\
FST::NODE(1, FST::RELATION('g', 6)),\
FST::NODE()

#define L_ACTIVITY 9,\
FST::NODE(1, FST::RELATION('a', 1)),\
FST::NODE(1, FST::RELATION('c', 2)),\
FST::NODE(1, FST::RELATION('t', 3)),\
FST::NODE(1, FST::RELATION('i', 4)),\
FST::NODE(1, FST::RELATION('v', 5)),\
FST::NODE(1, FST::RELATION('i', 6)),\
FST::NODE(1, FST::RELATION('t', 7)),\
FST::NODE(1, FST::RELATION('y', 8)),\
FST::NODE()

#define L_NEW 4, \
FST::NODE(1, FST::RELATION('n', 1)),\
FST::NODE(1, FST::RELATION('e', 2)),\
FST::NODE(1, FST::RELATION('w', 3)),\
FST::NODE()

#define L_GIVE 5, \
FST::NODE(1, FST::RELATION('g', 1)),\
FST::NODE(1, FST::RELATION('i', 2)),\
FST::NODE(1, FST::RELATION('v', 3)),\
FST::NODE(1, FST::RELATION('e', 4)),\
FST::NODE()


#define L_START 	6, \
FST::NODE(1, FST::RELATION('s', 1)),\
FST::NODE(1, FST::RELATION('t', 2)),\
FST::NODE(1, FST::RELATION('a', 3)),\
FST::NODE(1, FST::RELATION('r', 4)),\
FST::NODE(1, FST::RELATION('t', 5)),\
FST::NODE()

#define L_SEMICOLON 2, \
FST::NODE(1, FST::RELATION(';', 1)),\
FST::NODE()

#define L_COMMA 2, \
FST::NODE(1, FST::RELATION(',', 1)),\
FST::NODE()

#define L_BRACELEFT 2, \
FST::NODE(1, FST::RELATION('{', 1)),\
FST::NODE()

#define L_BRACERIGHT 2,\
FST::NODE(1,FST::RELATION('}', 1)),\
FST::NODE()

#define L_LEFTHESIS 2, \
FST::NODE(1, FST::RELATION('(', 1)),\
FST::NODE()

#define L_RIGHTHESIS 2, \
FST::NODE(1, FST::RELATION(')', 1)),\
FST::NODE()

#define L_VERB 	2, \
FST::NODE(6, FST::RELATION('+', 1), FST::RELATION('-', 1), FST::RELATION('*', 1), \
FST::RELATION('/', 1), FST::RELATION('=', 1),FST::RELATION('%',1)),\
FST::NODE()
#define L_LOOP 5, \
FST::NODE(1,FST::RELATION('L',1)),\
FST::NODE(1,FST::RELATION('O',2)),\
FST::NODE(1,FST::RELATION('O',3)),\
FST::NODE(1,FST::RELATION('P',4)),\
FST::NODE()

#define L_C_CHAR 5,\
FST::NODE(1,FST::RELATION('c',1)),\
FST::NODE(1,FST::RELATION('h',2)),\
FST::NODE(1,FST::RELATION('a',3)),\
FST::NODE(1,FST::RELATION('r',4)),\
FST::NODE()

#define L_C_INT 4,\
FST::NODE(1,FST::RELATION('i',1)),\
FST::NODE(1,FST::RELATION('n',2)),\
FST::NODE(1,FST::RELATION('t',3)),\
FST::NODE()

#define L_C_SHORT 6,\
FST::NODE(1,FST::RELATION('s',1)),\
FST::NODE(1,FST::RELATION('h',2)),\
FST::NODE(1,FST::RELATION('o',3)),\
FST::NODE(1,FST::RELATION('r',4)),\
FST::NODE(1,FST::RELATION('t',5)),\
FST::NODE()

#define L_C_STRING 6,\
FST::NODE(1,FST::RELATION('c',1)),\
FST::NODE(1,FST::RELATION('h',2)),\
FST::NODE(1,FST::RELATION('a',3)),\
FST::NODE(1,FST::RELATION('r',4)),\
FST::NODE(1,FST::RELATION('*',5)),\
FST::NODE()

#define L_OUTPUT 7,\
FST::NODE(1,FST::RELATION('o',1)),\
FST::NODE(1,FST::RELATION('u',2)),\
FST::NODE(1,FST::RELATION('t',3)),\
FST::NODE(1,FST::RELATION('p',4)),\
FST::NODE(1,FST::RELATION('u',5)),\
FST::NODE(1,FST::RELATION('t',6)),\
FST::NODE()

#define L_INTEGER 8,\
FST::NODE(1,FST::RELATION('i',1)),\
FST::NODE(1,FST::RELATION('n',2)),\
FST::NODE(1,FST::RELATION('t',3)),\
FST::NODE(1,FST::RELATION('e',4)),\
FST::NODE(1,FST::RELATION('g',5)),\
FST::NODE(1,FST::RELATION('e',6)),\
FST::NODE(1,FST::RELATION('r',7)),\
FST::NODE()